const PHOTOGRAPHERS = [
  {
    id: "p001",
    name: "Arjun Mehta Photography",
    slug: "arjun-mehta",
    tagline: "Where light meets emotion",
    city: "Mumbai",
    state: "Maharashtra",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=1200&q=85&auto=format&fit=crop",
    portfolioImages: [
      "https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=800&q=85&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=800&q=85&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&q=85&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=85&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800&q=85&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&q=85&auto=format&fit=crop",
    ],
    styles: ["Candid", "Cinematic", "Documentary"],
    services: ["Photography", "Videography", "Drone", "Same-day Edit"],
    experience: 10,
    weddings: 520,
    rating: 4.9,
    reviewCount: 248,
    verified: true,
    featured: true,
    available: true,
    basePrice: 85000,
    priceUnit: "per day",
    about: "Arjun Mehta has spent over a decade capturing the raw, unscripted emotions of weddings across India. His signature style blends cinematic storytelling with candid moments, creating images that feel like frames from a beautiful film. Every wedding is approached as a unique narrative — your love story told through light, colour, and authentic emotion.",
    equipment: ["Sony A7R V", "Canon EOS R5", "DJI Mavic 3 Drone", "Profoto Lighting"],
    awards: ["Best Wedding Photographer — WeddingWire 2023", "Top 10 Candid Photographers — India 2022"],
    packages: [
      {
        id: "pkg001",
        name: "Silver Memories",
        price: 85000,
        duration: "1 day coverage",
        popular: false,
        features: [
          "8 hours of photography",
          "1 lead photographer",
          "500+ edited images",
          "Online gallery delivery",
          "30-day delivery",
          "1 pre-wedding consultation",
        ],
      },
      {
        id: "pkg002",
        name: "Golden Legacy",
        price: 145000,
        duration: "2 day coverage",
        popular: true,
        features: [
          "16 hours of photography",
          "1 lead + 1 second photographer",
          "Cinematic wedding film (10 min)",
          "Drone coverage",
          "1000+ edited images",
          "Premium photo album",
          "Online gallery delivery",
          "21-day delivery",
          "2 pre-wedding consultations",
          "Complimentary engagement shoot",
        ],
      },
      {
        id: "pkg003",
        name: "Royal Chronicle",
        price: 220000,
        duration: "3 day coverage",
        popular: false,
        features: [
          "All functions coverage (Mehendi, Sangeet, Wedding)",
          "2 lead photographers + videographer",
          "Cinematic film (20 min) + teaser (3 min)",
          "Drone + same-day edit highlight",
          "2000+ edited images",
          "2 premium photo albums",
          "Canvas print (24x36)",
          "Online gallery for 1 year",
          "14-day delivery",
          "Unlimited consultations",
          "Complimentary pre-wedding shoot",
        ],
      },
    ],
    reviews: [
      {
        id: "rv001",
        name: "Priya & Rahul Sharma",
        avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&q=80&auto=format&fit=crop",
        rating: 5,
        date: "March 2024",
        title: "Beyond our wildest expectations",
        body: "Arjun has an extraordinary eye. He captured moments we didn't even know were happening — our parents' expressions during the pheras, stolen glances, tears we didn't notice. Every single photo is a masterpiece. We've already recommended him to 6 couples.",
      },
      {
        id: "rv002",
        name: "Sneha & Vikram Nair",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80&auto=format&fit=crop",
        rating: 5,
        date: "January 2024",
        title: "The best investment of our entire wedding",
        body: "We deliberated for months on budget. Choosing Arjun was the single best decision we made. The Golden Legacy package was perfect — the short film made our entire family cry. Delivered on time, professional at every step.",
      },
      {
        id: "rv003",
        name: "Aisha & Rohan Kapoor",
        avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80&auto=format&fit=crop",
        rating: 5,
        date: "November 2023",
        title: "Cinematic magic",
        body: "The teaser film Arjun produced had 40,000 views on Instagram within 48 hours. People couldn't believe how beautiful it was. He's a true artist, not just a photographer.",
      },
    ],
  },
  {
    id: "p002",
    name: "Studio Lumière",
    slug: "studio-lumiere",
    tagline: "Crafting timeless wedding art",
    city: "Delhi",
    state: "Delhi",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=1200&q=85&auto=format&fit=crop",
    portfolioImages: [
      "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=800&q=85&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=800&q=85&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800&q=85&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&q=85&auto=format&fit=crop",
    ],
    styles: ["Traditional", "Candid", "Editorial"],
    services: ["Photography", "Videography", "Pre-Wedding"],
    experience: 7,
    weddings: 340,
    rating: 4.8,
    reviewCount: 182,
    verified: true,
    featured: true,
    available: true,
    basePrice: 65000,
    priceUnit: "per day",
    about: "Studio Lumière is a boutique wedding photography collective based in Delhi. Founded by renowned photographer Ishaan Kapur, the studio specialises in blending traditional Indian wedding aesthetics with contemporary editorial styling.",
    equipment: ["Canon EOS R5", "Nikon Z9", "Medium Format Hasselblad"],
    awards: ["Best Wedding Studio — DelhiWeds 2023"],
    packages: [
      {
        id: "pkg004", name: "Essentials", price: 65000,
        duration: "1 day", popular: false,
        features: ["8 hrs photography", "400+ edited images", "Online delivery", "30-day turnaround"],
      },
      {
        id: "pkg005", name: "Signature", price: 120000,
        duration: "2 days", popular: true,
        features: ["Full 2-day coverage", "800+ edited images", "Short film", "Album", "21-day turnaround"],
      },
    ],
    reviews: [
      {
        id: "rv004", name: "Meera & Arjun Patel",
        avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80&auto=format&fit=crop",
        rating: 5, date: "February 2024",
        title: "Editorial perfection",
        body: "Studio Lumière gave our wedding photos a magazine-worthy quality. Every photo is composition-perfect. Ishaan has an incredible sense for lighting and timing.",
      },
    ],
  },
  {
    id: "p003",
    name: "Rishi Frames",
    slug: "rishi-frames",
    tagline: "South India's story, beautifully told",
    city: "Chennai",
    state: "Tamil Nadu",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=85&auto=format&fit=crop",
    portfolioImages: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=85&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&q=85&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=800&q=85&auto=format&fit=crop",
    ],
    styles: ["Traditional", "Candid"],
    services: ["Photography", "Videography"],
    experience: 5,
    weddings: 210,
    rating: 4.6,
    reviewCount: 134,
    verified: true,
    featured: false,
    available: true,
    basePrice: 45000,
    priceUnit: "per day",
    about: "Rishi Frames specialises in South Indian wedding traditions — from vibrant Kanchipuram sarees to sacred rituals — capturing the beauty and devotion of each ceremony with deep cultural sensitivity.",
    equipment: ["Sony A7 IV", "Canon EOS R6"],
    awards: [],
    packages: [
      {
        id: "pkg006", name: "Classic", price: 45000,
        duration: "1 day", popular: false,
        features: ["8 hrs photography", "300+ edited images", "Online gallery"],
      },
      {
        id: "pkg007", name: "Complete", price: 80000,
        duration: "2 days", popular: true,
        features: ["Full ceremony coverage", "600+ edited images", "Short film", "Album"],
      },
    ],
    reviews: [
      {
        id: "rv005", name: "Kavya & Siddharth Rajan",
        avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&q=80&auto=format&fit=crop",
        rating: 5, date: "April 2024",
        title: "Captured our traditions beautifully",
        body: "Rishi understood every ritual without explanation. His coverage of our Muhurtham and Saptapadi was so reverent and beautiful. Highly recommend for South Indian weddings.",
      },
    ],
  },
  {
    id: "p004",
    name: "Golden Hour Studios",
    slug: "golden-hour-studios",
    tagline: "Every frame, a lifetime",
    city: "Bangalore",
    state: "Karnataka",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=1200&q=85&auto=format&fit=crop",
    portfolioImages: [
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&q=85&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800&q=85&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=800&q=85&auto=format&fit=crop",
    ],
    styles: ["Candid", "Documentary", "Fine Art"],
    services: ["Photography", "Drone", "Same-day Edit"],
    experience: 8,
    weddings: 390,
    rating: 4.7,
    reviewCount: 205,
    verified: true,
    featured: true,
    available: false,
    basePrice: 70000,
    priceUnit: "per day",
    about: "Golden Hour Studios is Bangalore's most sought-after wedding photography collective, led by award-winning photographer Kiran Das. Known for breathtaking natural light work and fine-art compositions.",
    equipment: ["Sony A1", "Leica Q3", "DJI Air 3"],
    awards: ["Karnataka Best Wedding Photographer 2023"],
    packages: [
      {
        id: "pkg008", name: "Twilight", price: 70000,
        duration: "1 day", popular: false,
        features: ["8 hrs coverage", "400+ edited images", "Online gallery"],
      },
      {
        id: "pkg009", name: "Sunrise", price: 130000,
        duration: "2 days", popular: true,
        features: ["16 hrs coverage", "900+ images", "Cinematic film", "Drone", "Album"],
      },
    ],
    reviews: [
      {
        id: "rv006", name: "Pooja & Nikhil Mehta",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80&auto=format&fit=crop",
        rating: 5, date: "March 2024",
        title: "Art, not just photos",
        body: "Kiran sees light like no one else. Our wedding photos look like they belong in an art gallery. We've framed 12 of them around our home.",
      },
    ],
  },
  {
    id: "p005",
    name: "Brij & Co. Photography",
    slug: "brij-co",
    tagline: "Royally yours, frame by frame",
    city: "Jaipur",
    state: "Rajasthan",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&q=80&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=1200&q=85&auto=format&fit=crop",
    portfolioImages: [
      "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800&q=85&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=800&q=85&auto=format&fit=crop",
    ],
    styles: ["Candid", "Traditional", "Cinematic"],
    services: ["Photography", "Videography", "Drone"],
    experience: 12,
    weddings: 640,
    rating: 5.0,
    reviewCount: 310,
    verified: true,
    featured: true,
    available: true,
    basePrice: 95000,
    priceUnit: "per day",
    about: "Brij & Co. is Rajasthan's premier wedding photography house with over 12 years of experience documenting destination weddings at India's most iconic palace venues.",
    equipment: ["Hasselblad X2D", "Sony A7R V", "DJI Mavic 3 Pro"],
    awards: ["Rajasthan Best Wedding Photographer 2022 & 2023", "WedMeGood Top 50 India"],
    packages: [
      {
        id: "pkg010", name: "Heritage", price: 95000,
        duration: "1 day", popular: false,
        features: ["8 hrs photography", "600+ edited images", "Album"],
      },
      {
        id: "pkg011", name: "Palace", price: 175000,
        duration: "2-3 days", popular: true,
        features: ["Multi-day coverage", "1500+ images", "Cinematic film", "Drone", "2 albums", "Same-day edit"],
      },
    ],
    reviews: [
      {
        id: "rv007", name: "Zara & Imran Sheikh",
        avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80&auto=format&fit=crop",
        rating: 5, date: "December 2023",
        title: "The only photographer for palace weddings",
        body: "Brij knows every corner, every light of the Rajasthan palaces. Our photos at Rambagh Palace are beyond description. Worth every paisa and more.",
      },
    ],
  },
  {
    id: "p006",
    name: "Pixel Prism Studios",
    slug: "pixel-prism",
    tagline: "Colour, light & pure joy",
    city: "Hyderabad",
    state: "Telangana",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=1200&q=85&auto=format&fit=crop",
    portfolioImages: [
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&q=85&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=85&auto=format&fit=crop",
    ],
    styles: ["Candid", "Editorial"],
    services: ["Photography", "Videography"],
    experience: 6,
    weddings: 280,
    rating: 4.5,
    reviewCount: 156,
    verified: true,
    featured: false,
    available: true,
    basePrice: 55000,
    priceUnit: "per day",
    about: "Pixel Prism Studios brings vibrant, colour-rich photography to every wedding. Based in Hyderabad, the team specialises in capturing the joy, chaos and beauty of Indian weddings.",
    equipment: ["Canon EOS R5", "Sony FX3"],
    awards: [],
    packages: [
      {
        id: "pkg012", name: "Prism Basic", price: 55000,
        duration: "1 day", popular: false,
        features: ["8 hrs coverage", "350+ images", "Online gallery"],
      },
      {
        id: "pkg013", name: "Prism Premium", price: 100000,
        duration: "2 days", popular: true,
        features: ["2-day coverage", "700+ images", "Film", "Drone", "Album"],
      },
    ],
    reviews: [
      {
        id: "rv008", name: "Sunita & Dev Khanna",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80&auto=format&fit=crop",
        rating: 5, date: "January 2024",
        title: "Vibrant and joyful photography",
        body: "The colours in our photos are so vivid and alive. The team captured every bit of fun and emotion from our three-day wedding.",
      },
    ],
  },
];

export const photographerService = {
  getAll: ({ city, priceMax, experienceMin, style, sort } = {}) => {
    let results = [...PHOTOGRAPHERS];
    if (city && city !== "all")
      results = results.filter(p => p.city.toLowerCase() === city.toLowerCase());
    if (priceMax)
      results = results.filter(p => p.basePrice <= Number(priceMax));
    if (experienceMin)
      results = results.filter(p => p.experience >= Number(experienceMin));
    if (style && style !== "all")
      results = results.filter(p => p.styles.map(s => s.toLowerCase()).includes(style.toLowerCase()));
    switch (sort) {
      case "price_asc":  results.sort((a, b) => a.basePrice - b.basePrice); break;
      case "price_desc": results.sort((a, b) => b.basePrice - a.basePrice); break;
      case "rating":     results.sort((a, b) => b.rating - a.rating);       break;
      case "experience": results.sort((a, b) => b.experience - a.experience); break;
      default:           results.sort((a, b) => b.featured - a.featured);   break;
    }
    return results;
  },
  getById:   (id) => PHOTOGRAPHERS.find(p => p.id === id || p.slug === id) || null,
  getSimilar: (id) => PHOTOGRAPHERS.filter(p => p.id !== id).slice(0, 3),
  getCities:  ()  => [...new Set(PHOTOGRAPHERS.map(p => p.city))],
};